version: "3.7"

services:
    web:
        image: nginx:latest
        container_name: web
        ports:
            - "8080:80"
        volumes:
            - ./:/usr/share/nginx/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        build: ./docker/php
        container_name: php
        volumes:
            - ./:/usr/share/nginx/html
            - ./docker/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
#        environment:
#            PHP_IDE_CONFIG: "serverName=PhpServerBase"
        extra_hosts:
            - host.docker.internal:172.17.0.1
        links:
            - db
        expose:
            - 9000
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8090:80"
        links:
            - db
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PMA_HOST: db
    db:
        image: mysql:8.0.20
        container_name: db
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'user'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: ''
#            MYSQL_ROOT_HOST: $ROOT_HOST
        restart: always
